stages:
  - test


default:
  image: node:lts-bookworm-slim
  cache:  # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/

lint:
  stage: test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - "**/*.js"
        - "**/*.mjs"
        - "**/*.cjs"
        - .gitlab-ci.yml
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run lint
  after_script: 
    - echo "🚩 You can fix lint errors by running 'npx prettier --write .' and  'npx eslint --fix .'"
  allow_failure: false
